version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    allow:
      - dependency-type: all
    open-pull-requests-limit: 50000

  - package-ecosystem: cargo
    directory: src-tauri
    schedule:
      interval: monthly
    allow:
      - dependency-type: all
    open-pull-requests-limit: 50000
